# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llinsolve <- function(A, b) {
    .Call('_gfimmCPP_llinsolve', PACKAGE = 'gfimmCPP', A, b)
}

tsolveAndMultiply <- function(A, C) {
    .Call('_gfimmCPP_tsolveAndMultiply', PACKAGE = 'gfimmCPP', A, C)
}

nullSpace <- function(M) {
    .Call('_gfimmCPP_nullSpace', PACKAGE = 'gfimmCPP', M)
}

QRdecomp <- function(M) {
    .Call('_gfimmCPP_QRdecomp', PACKAGE = 'gfimmCPP', M)
}

whichLU <- function(V, L, U) {
    .Call('_gfimmCPP_whichLU', PACKAGE = 'gfimmCPP', V, L, U)
}

main <- function() {
    .Call('_gfimmCPP_main', PACKAGE = 'gfimmCPP')
}

ListOfGmatrices <- function(nrows, ncols, nmatrices) {
    .Call('_gfimmCPP_ListOfGmatrices', PACKAGE = 'gfimmCPP', nrows, ncols, nmatrices)
}

temp <- function(n) {
    .Call('_gfimmCPP_temp', PACKAGE = 'gfimmCPP', n)
}

